### ISSUE TITLE
PHP-Error - Use of undefined constant GROCY_USER_ID

### ISSUE THREAD

**Issue by dbxx** [berrnd/grocy#96]
I'm on shared hosting. When i use the PHP Version 7.2.8 I get this PHP error:

`Warning: Use of undefined constant GROCY_USER_ID - assumed 'GROCY_USER_ID' (this will throw an Error in a future version of PHP) in /home/www/grocy/controllers/BaseController.php on line 47`

When i choose PHP Version 7.1.20 it seems fine. No such error messsage.

**Comment by berrnd** [comment]
Is (for now) only a warning, so should be no problem, and is also already fixed in https://github.com/berrnd/grocy/commit/f13abf483ebaa5e5d5317b9c15ee57a0cefbad6f (not part of a released version yet).

**Comment by AntouanK** [comment]
I still get that ( just used the https://github.com/grocy/grocy-docker/ to run it )

![Screenshot from 2020-03-21 18-13-23](https://user-images.githubusercontent.com/4569111/77232192-d2dea480-6b9f-11ea-8cf8-4a769103323d.png)

**Comment by berrnd** [comment]
And I still don't really care about warnings (disable them, `php.ini`).
